### ISSUE TITLE
kail 2.0 执行不成功

### ISSUE THREAD

**Issue by icezhaoL** [ring04h/wydomain#14]
root@kali:~/wydomain# python wydomain.py baidu.com\

> ---
> ## \* Starting fofa plugin search
> 
> Traceback (most recent call last):
>   File "wydomain.py", line 346, in <module>
>     print start_wydomain(sys.argv[1])
>   File "wydomain.py", line 53, in start_wydomain
>     fofa_result = start_fofa_plugin(domain)
>   File "/root/wydomain/fofaplugin.py", line 244, in start_fofa_plugin
>     get_partner_domain(domain)
>   File "/root/wydomain/fofaplugin.py", line 181, in get_partner_domain
>     jobId = json.loads(taskinfo)['jobId']
>   File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

**Comment by ring04h** [comment]
用新版本吧
