### ISSUE TITLE
新版本依旧报错

### ISSUE THREAD

**Issue by zhangzhishan** [ring04h/wydomain#17]
`
Traceback (most recent call last):
  File "wydomain.py", line 149, in <module>
    run(args)
  File "wydomain.py", line 89, in run
    logging.info("chaxunla fetcher subdomains({0}) successfully...".format(len(result)))
TypeError: object of type 'NoneType' has no len()

`

**Comment by ring04h** [comment]
恩，chaxunla会检测IP，并屏蔽，我加个控制

**Comment by ring04h** [comment]
因为result.get('status') == 3, 屏蔽后一直出错，导致没有值return，
现在改成不管怎样都 return list(set(self.subset))
