### ISSUE TITLE
api.ysdm.net get verify_code failed

### ISSUE THREAD

**Issue by UncleJim** [ring04h/wydomain#19]
[INFO] Starting new HTTP connection (1): api.ysdm.net
('get verify_code():', None)

**Comment by ring04h** [comment]
为了防止chaxun.la网站的封禁，使用了自动识别验证码的平台
结果已经没钱啦。

**Comment by ring04h** [comment]
chaxun.la 对请求频率过高的ip，要人工输入验证码，代码嵌入了[云速打码]自动识别验证码的功能，但是多人公用账号，导致我的账号被封禁了，所以临时关闭人机绕过功能，如果需要开启，你们可以注册使用自己账号。

https://github.com/ring04h/wydomain/blob/wydomain2/captcha.py
https://github.com/ring04h/wydomain/blob/wydomain2/utils/chaxunla.py#L41
