### ISSUE TITLE
使用中的小问题

### ISSUE THREAD

**Issue by lupus721** [ring04h/wydomain#20]
1 使用chaxun的api，有时候好有时候不好，没有超过额度，也是一天之内使用的cookie应该不会过期，('Connection aborted.', error(104, 'Connection reset by peer'))

2 我有一个列表批量查询的时候怎么做，或者我想要即使用字典又使用API能一个命令搞定么

3 看到 netcraft貌似最多只有500条记录，如果我想抓所有的.edu.cn的域名这500个明显是不够的，或者这种情况下怎么使用这个工具。或者是这个工具只是针对二级域名，对根域名不是很好。

4 使用过程中还提示
 [INFO] Starting new HTTPS connection (1): www.threatminer.org
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning

**Comment by ring04h** [comment]
1. chaxun的api是可以用打码平台，绕过验证码的，你可以看具体的代码实现，只是我注释掉了。
2. 把他们分开，是想解耦和，你可以先python dnsburte.py -d aliyun.com 之后，会生成result/aliyun.com/dnsburte.json, 然后再执行 python wydomain.py -d aliyun.com ，代码里面回去读取dnsburte的结果，再去重生成最终的结果集的。
3. netcraft是可以做到大于500条记录的，需要使用phantomjs来生成新的cookie，安装一个phantomjs就可以了。

**Comment by ring04h** [comment]
4 这个是Mac OS X的openssl问题，可以使用命令行调用curl解决，我本机的就是调用的这个方法。
https://github.com/ring04h/wydomain/blob/wydomain2/common.py#L64

**Comment by lupus721** [comment]
谢谢
