### ISSUE TITLE
域名穷举结果为空

### ISSUE THREAD

**Issue by sadk** [ring04h/wydomain#23]
我用2个线程 domain_larger.csv字典去尝试穷举 youku.com的域名，发现穷举结果为空。麻烦帮忙看一下什么原因。

**Comment by sadk** [comment]
使用环境是osx + python 2.7

**Comment by sadk** [comment]
已经找到问题了，字典是windows的换行符。

utils\fileutils.py 99行 修改如下

`yield line.replace('\n', '').replace('\r','')`

**Comment by sadk** [comment]
另外两个bug
dnsburte.py

117行改为:

`print(target, rdtype, '<timeout>')`

139行改为:

`return self.query(target,'A') # timeout retry`

**Comment by sadk** [comment]
另外 ctrl c 不可用

**Comment by ring04h** [comment]
OK，修改列表都记下了，本周末同步代码。
